# Generated by Django 4.0.5 on 2022-06-25 15:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['name', 'surname'],
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_russian', models.CharField(help_text='Введите название на русском языке', max_length=150, verbose_name='Название книги')),
                ('title_foreign', models.CharField(blank=True, help_text='Введите название на иностранном языке', max_length=150, null=True, verbose_name='Название на иностранном языке')),
                ('description', models.TextField(help_text='Введите описание книги', max_length=1000, verbose_name='Краткое описание книги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('cost_daily', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за день использования')),
                ('amount_ex', models.IntegerField()),
                ('available_ex', models.IntegerField()),
                ('date_registration', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('number_of_pages', models.IntegerField(blank=True, null=True, verbose_name='Количество страниц')),
                ('year_of_publication', models.DateField(blank=True, null=True, verbose_name='Дата публикации')),
                ('pubdate', models.DateTimeField(auto_now_add=True)),
                ('author', models.ManyToManyField(to='main.author', verbose_name='Авторы')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['title_russian', '-pubdate'],
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('second_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('ages', models.IntegerField(verbose_name='Возраст')),
                ('sex', models.CharField(choices=[('Male', 'Man'), ('Female', 'Woman')], default='Male', max_length=7, verbose_name='Пол')),
                ('number_of_passport', models.CharField(max_length=9, unique=True, verbose_name='Номер паспорта')),
                ('place', models.CharField(max_length=30, verbose_name='Город проживания')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['name', 'surname'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите', max_length=50, unique=True, verbose_name='Название жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImageBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/book', verbose_name='Изображение книги')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.books')),
            ],
            options={
                'verbose_name': 'Изображения книги',
                'verbose_name_plural': 'Изображения книг',
            },
        ),
        migrations.CreateModel(
            name='ImageAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/author', verbose_name='Фотография автора')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.author', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Изображение автора',
                'verbose_name_plural': 'Изображения авторов',
            },
        ),
        migrations.AddField(
            model_name='books',
            name='customers_books',
            field=models.ManyToManyField(blank=True, null=True, to='main.customers', verbose_name='Клиенты'),
        ),
        migrations.AddField(
            model_name='books',
            name='genre',
            field=models.ManyToManyField(to='main.genre', verbose_name='Жанр'),
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('22519089-455f-4012-9488-0612b637b546'), primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('due_back', models.DateField(blank=True, null=True, verbose_name='Дата возврата')),
                ('status', models.CharField(blank=True, choices=[('m', 'На обслуживании'), ('o', 'Нет в наличии'), ('a', 'В наличии'), ('r', 'Зарезервирована')], default='m', max_length=10, verbose_name='Статус')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.books', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Копия',
                'verbose_name_plural': 'Экземпляры книг',
                'ordering': ['book', 'due_back'],
            },
        ),
    ]
